### ISSUE TITLE
janus-gateway >= 1.0 support

### ISSUE THREAD

**Issue by arpu** [foxford/ulms-backend#111]
Hey,

i wonder if you have plans to support multistream janus 1.0 ? 

idea would be to support multiple video and audio streams

**Comment by arpu** [comment]
i would interested to work on this together, if possible

**Comment by manifest** [comment]
Hey @arpu,

It is not our priority at the moment, but we would love to get there eventually.

First thing towards this goal would be to update [janus-plugin-rs](https://github.com/mozilla/janus-plugin-rs) crate. It is currently unmaintained.

Are you considering working on it?

**Comment by arpu** [comment]
Hey @manifest ,

what we have in networked-aframe is https://github.com/networked-aframe/janus-plugin-rs  at the moment

**Comment by manifest** [comment]
I see. That's a start :-)

**Comment by arpu** [comment]
Would love to get to the next stage with this, because screensharing + audio and webcam + mic  at same time, would be nice

**Comment by manifest** [comment]
I'll close this issue since we don't have throughput for this at the moment. Let's be in touch.
